### ISSUE TITLE
[pt-BR] Error in translation (“editor” translated as “organizador”; should be “editor”)

### ISSUE THREAD

**Issue by guslaet** [citation-style-language/locales#284] opened 2023-04-17 17:47 UTC
**locales-pt-BR.xml** is translating entries related to “editor” to “organizador” (= organizer), whereas there is the figure of the editor, which is different from the organizer.

These are the places that need correction:

```
    <term name="editor">
      <single>organizador</single>
      <multiple>organizadores</multiple>
    </term>
    <term name="editorial-director">
      <single>editor</single>
      <multiple>editores</multiple>
    </term>

[...]

    <term name="editor" form="short">
      <single>org.</single>
      <multiple>orgs.</multiple>
    </term>

[...]

    <term name="editor" form="verb">organizado por</term>

[...]

    <term name="editor" form="verb-short">org.</term>
```

Should be

```
    <term name="editor">
      <single>editor</single>
      <multiple>editores</multiple>
    </term>
    <term name="editorial-director">
      <single>diretor editorial</single>
      <multiple>diretores editoriais</multiple>
    </term>

[...]

    <term name="editor" form="short">
      <single>ed.</single>
      <multiple>eds.</multiple>
    </term>

[...]

    <term name="editor" form="verb">editado por</term>

[...]

    <term name="editor" form="verb-short">ed.</term>
```
(By the way: the pt-PT xml is correct.)

**Comment by bwiernik** [comment] 2023-04-17 19:43
Editorial Director refers to the role of someone who manages the solicitation of chapters and publication process for a book--"directeur de la publication" in French--would "organizador" be correct for that role?

**Comment by adam3smith** [comment] 2023-04-17 19:47
The problem is that we a) have a fair number of Brazilian styles relying on the organizador translation, 
and b) no reference manager has a field for editorial-director (and I don't believe you can even get editorial-manager to work at all in Mendeley Cite, they most common reference manager ins Brazil), making it impossible to get chapters from edited volumes right without translating editor as organizador. Edited books (in the sense of editeur in French) are much less common.

**Comment by guslaet** [comment] 2023-04-17 20:05
a) But you already have the “Organizador” (= organizer) term/role for that.
b) True. And probably no Brazilian scholar is missing that (editorial-director / diretor editorial) role.

I don’t think I follow your argument when you say “making it impossible to get chapters from edited volumes right without translating editor as organizador”. Although there is a good number of books where the person who gathers the articles is called “Organizador”, there are as well several books where that role is given to the “Editor” as well. The amount probably depends on the field. Some might user org. more frequently, some ed.

Plus, if we force org. to a person who is assigned the role of editor in a given book (including books from other languages and regions), we would be forcing a mistake. To my view it is better to have the Reference Manager apps to deal with that than to translate editor as “organizador”.

**Comment by adam3smith** [comment] 2023-04-17 20:46
The term organizer is for an organizer of an event, like a panel, so that doesn't apply here (though could have the same translation to Portuguese, I don't know).

But for the correct citation of editor: if you take a citation like

ROMERO, Sonia Mara Thater; SILVA, Selma França da Costa E. Gestão da qualidade de vida no trabalho. In: ROMERO, Sonia Mara Thater; SILVA, Selma França da Costa e; KOPS, Lucia Maria (org.). Gestão de pessoas: conceitos e estratégias. Curitiba: InterSaberes, 2013. p. 139–154.

(via https://www.ufrgs.br/bibliotecas/ferramentas/campos-basicos-abnt-zotero/#capitulo ), Romero, Silva, and Kops are editors in English, organizadores in Portugese, so organizador is absolutely a correct translation of the English "editor" in some situations -- the question of whether it's the _best_ translation is trickier, but it seems widely preferred within the Brazilian citation styles. 
And beyond that my question remains: how would you generate the above citation with data entered correctly in a reference manager?

**Comment by guslaet** [comment] 2023-04-17 20:58
Well, in most cases, many of these books come from events **organized** by these people, so if the organizer role is for organizing events, it applies to them as well.

Anyway, regarding the particular entry, I could ask you the same question regarding this one:

WARREN, J. Coming-to-be and passing-away: M 10.310–351. Em: ALGRA, K.; IERODIAKONOU, K. (Eds.). Sextus Empiricus and Ancient Physics. Cambridge: Cambridge University Press, 2015. p. 365–402. 

The books says *explicitly* that Algra and Ierodiakonou are **editors**.

I'd say this is a draw. And that is because the problem here is not of translation, but of functionality in Reference Managing apps. Perhaps we could try to fill a .bib file manually with the role of organizer and see how citeproc for instance behave.

Anyhow, it just doesn’t seem right to me in principle to solve an application functionality problem by hacking translations in a locales file. A good place for such a workaround would be to override the locale information in the CSL file directly. That is what I've done to get my EDS. instead of ORGS. that come from this file.

**Comment by bwiernik** [comment] 2023-04-18 01:27
.bib isn't a format that's used by CSL styles or any citeproc--organizer isn't a CSL variable

**Comment by adam3smith** [comment] 2023-04-18 01:39
(we added organizer in 1.0.2)

**Comment by adam3smith** [comment] 2023-04-18 02:28
> Anyhow, it just doesn’t seem right to me in principle to solve an application functionality problem by hacking translations in a locales file.  

Again, this is a misunderstanding. This is not a hack, and there's no reason that the word with the same Latin root is the best translation between English and Portuguese and English. In the context of citations, the Portuguese _organizador_ is absolutely _one_ completely accurate translation of the English _editor_. If you want an explicit example, here's the original of a chapter by Dolan in a book edited by R. Crandall & P. L. Perrewé. Note they're labeled as (Eds.) in the citation at the top
https://psycnet.apa.org/record/1995-97235-016 
Now check the citation to the same work in a Brazilian social science journal I picked out from Scielo at random
https://www.scielo.br/j/ptp/a/zngrNHmyWTRynf8XGJGVGYc/?lang=pt
Dolan, S. L. (1995). Individual, organizational and social determinants of managerial burnout: Theorical and empirical update. Em R. Crandall & P. L. Perrewé (Orgs.), Occupational stress handbook (pp. 223-237). Washington: Taylor & Francis.

Now, I'm open to be convinced that the Portuguese _editor_ is a _better_ translation -- in the sense that it is more commonly used in places where English would use editor: guidance from authoritative citation guidelines, especially ABNT, would be particularly relevant for that. But if you want to argue that it's the one correct translation, that's obviously false and it's not going to get us anywhere.

**Comment by guslaet** [comment] 2023-04-18 10:32
Now this is not exactly true: “there's no reason that the word with the same Latin root is the best translation between English and Portuguese and English”. It would be more precise to say that “the sharing of the same Latin root is not **sufficient** reason to decide upon a translation from English to Portuguese”, since, in fact, the sharing of a Latin root is a **very good** reason to keep Portuguese close to Latin in cases like this, Portuguese being, as you know, a Latin language.

Moreover, right or wrong translations depend largely on context, and lack of context is exactly the problem here. We could discuss particular examples forever. They won’t prove your point, nor mine.

When I say lack of context, I speak generally. The terms defined in these locales files can be applied in different contexts which you cannot control *a priori*. That is probably one of the reasons why new terms keep being added: to deal with different uses that come up along the way.

I understand your point: there is a good number of cases in which the role described in English by the word ‘editor’ is either the same or at least pretty much analogous to the role described by the Portuguese word ‘organizador’ in academic publishing. However, there are two points here that must be taken into account:

First, the people responsible for these collections of articles can have two different “sub-roles”:

a. In one of them, they act as mere collectors (from academic conferences, for instance), and do not interfere with the contents of the collected articles. In this case, these books are analogous to annals. This role is certainly closer to the meaning of the Portuguese word ‘organizador’ than the Portuguese word ‘editor’.

b. However, there is also the case in which they act as requesters of content and effectively interfere in the requested text, as in a regular *editorial* process. Their interference, however, is not enough to turn them into co-authors, but is certainly greater than that of a *mere* organizer-collector. In such cases, they should correctly be referred to as ‘editores’.

The second point is the fact that the understanding and interpretation of these roles cannot be controlled and will inexorably vary based on the research contexts and fields. And that is actually another reason why people should have the possibility to *decide* which term they will use, depending on their contexts and evaluation of the cases they have at hand.

You can of course invoke some authority such as ABNT to decide it. I wouldn’t do that because such authorities have their own biases and limitations. For me, however, the best practice seems to be to be able to *support* whatever ABNT has to say regarding the things they normalize, but also to be able to *support* situations they have not [yet] predicted, or decided to ignore, either because they do not happen so often, or due to some prejudice.

Last, but not least, I’d like to point out that the pt-PT version of this locales files translates ‘editor’ (en) to ‘editor’ (pt) and ‘organizer’ (en) to ‘organizador’ (pt), as I suggested. pt-PT translations are no ABNT, of course, but in Portugal they certainly know their Portuguese very well and should not be ignored.

Another comment: after I opened this issue #284, I tried to fork the file and propose the change directly. However, when to me it loaded a different version than the current one. I’m not a frequent user of Git, but it seemed to me it loaded some newer version that was awaiting approval for some other change. In that version ‘editor’ (en) was translated to ‘editor’ (pt) (or so it seemed to me), so that there was nothing I needed to change, and for that reason I simply dropped it.

Regarding this particular issue #284, I don’t think we need to continue this discussion. I myself have found a workaround, as I mentioned, overriding the locale tag in my CSL file. So I can close the issue, if you agree.

**Comment by adam3smith** [comment] 2023-04-19 01:52
Yeah, I hadn't realized we had org/organizador for 12+ years. 
I understand the overall situation isn't ideal and does indeed go back to the fact that English (and several other European languages, at a minimum) used a single word (e.g. editor in English, Herausgeber in German) for tasks that are arguably quite distinct. Other countries don't. Volume is another example for this. We currently don't have a great way of dealing with this beyond picking the best (in the sense of 'most common') option in translation, and I'm pretty sure that's org. here, so closing this -- happy to discuss more general approaches to this issue on discourse.citationstyles.org .

**Closed by adam3smith** 2023-04-19 01:52 UTC
Labels: waiting-for-response-from-contributor
